ticket_server_cors_allow_origins = ["https://data.umccr.org", "https://data.dev.umccr.org"]
ticket_server_cors_max_age = 300

data_server_enabled = false

name = "umccr-htsget-rs"
version = "0.1"
organization_name = "UMCCR"
organization_url = "https://umccr.org/"
contact_url = "https://umccr.org/"
documentation_url = "https://github.com/umccr/htsget-rs"
environment = "dev"

[[resolvers]]
regex = '^umccr-10c-data-dev/(?P<key>.*)$'
substitution_string = '$key'
storage_type = { type = 'S3', bucket = 'umccr-10c-data-dev' }

[[resolvers]]
regex = '^umccr-10f-data-dev/(?P<key>.*)$'
substitution_string = '$key'
storage_type = { type = 'S3', bucket = 'umccr-10f-data-dev' }

[[resolvers]]
regex = '^umccr-10g-data-dev/(?P<key>.*)$'
substitution_string = '$key'
storage_type = { type = 'S3', bucket = 'umccr-10g-data-dev' }

[[resolvers]]
regex = '^umccr-agha-test-dev/(?P<key>.*)$'
substitution_string = '$key'
storage_type = { type = 'S3', bucket = 'umccr-agha-test-dev' }

[[resolvers]]
regex = '^umccr-research-dev/(?P<key>.*)$'
substitution_string = '$key'
storage_type = { type = 'S3', bucket = 'umccr-research-dev' }

[[resolvers]]
regex = '^umccr-primary-data-dev/(?P<key>.*)$'
substitution_string = '$key'
storage_type = { type = 'S3', bucket = 'umccr-primary-data-dev' }