ticket_server_cors_allow_headers = "All"
ticket_server_cors_allow_origins = [
    "https://htsget.demo.umccr.org",
]
ticket_server_cors_allow_methods = "All"
ticket_server_cors_allow_credentials = true
ticket_server_cors_max_age = 300

data_server_enabled = false

name = "umccr-htsget-rs"
version = "0.1"
organization_name = "UMCCR"
organization_url = "https://umccr.org/"
contact_url = "https://umccr.org/"
documentation_url = "https://github.com/umccr/htsget-rs"
environment = "public"

[[resolvers]]
regex = '^(org.umccr.demo.sbeacon-data)/CINECA_UK1/(?P<key>.*)$'
substitution_string = 'CINECA_UK1/$key'

[[resolvers]]
regex = '^(org.umccr.demo.htsget-rs-data)/data/bam|cram|vcf|bcf|crypt4gh/(?P<key>.*)$'
substitution_string = '$key'
