name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust: [stable]
        os: [ubuntu-latest]
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          # Todo: remove this when clippy introduces https://github.com/rust-lang/rust-clippy/pull/10865 in nightly or stable.
          toolchain: 1.69
          # toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy
      - name: Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: build-cache
          save-if: ${{ github.ref == 'refs/heads/main' }}
      - name: Build all features
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-targets --all-features
      - name: Build no default features
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-targets --no-default-features
      - name: Build s3-storage
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-targets --features s3-storage
      - name: Build url-storage
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-targets --features url-storage
